### ISSUE TITLE
Cannot modify POI name in expert mode

### ISSUE THREAD

**Issue by bagage** [jawg/osm-contributor#70] opened 2016-11-20 09:22 UTC
**Description:**
When trying to edit the name of an existing POI, whenever you validate your modification the name reverts to the previous existing value.

**Steps to reproduce:**

1. Enable Expert mode
2. Download some POI and edit `name` field. Once you're happy with the new name, close the keyboard/validate it.

**Expected behavior:**
The value for `name` should be the newly entered input.

**Actual behavior:**
The value for `name` actually resets to the previous value, as if I did not edited it.

**Environment:**
Xiaomi Redmi 3, Android 5.1.1 with custom ROM MIUI 7.3

**Version:**
Current playstore version, 3.0.0.

**Comment by Hugoo13** [comment] 2017-01-12 12:51
Duplicate of #66 ? Should be fixed in next release in a few days!

**Closed by Hugoo13** 2017-01-12 12:51 UTC
